apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rbo8lhix5-nodejs
  janus-idp.io/tekton: rbo8lhix5-nodejs
  backstage.io/kubernetes-id: rbo8lhix5-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rbo8lhix5-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
